from pathlib import Path

import numpy as np
import pytest
from scipy.spatial.transform import Rotation as R

from epa.core.io_utils import (
    load_estimation_kitti,
    load_estimation_trajectory,
    load_estimation_tum,
    load_reference_trajectory,
    load_vicon_csv,
    make_output_dir,
    write_run_reports,
    write_result_bundle,
)
from epa.core.outputs import write_pose_state_csv


def test_load_estimation_tum(tmp_path: Path) -> None:
    traj_path = tmp_path / "traj.tum"
    traj_path.write_text(
        "# t tx ty tz qx qy qz qw\n"
        "0 0 0 0 0 0 0 1\n"
        "1 1 0 0 0 0 0 1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_tum(traj_path)

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_tum_accepts_comma_delimited_text(tmp_path: Path) -> None:
    traj_path = tmp_path / "traj.txt"
    traj_path.write_text(
        "timestamp tx ty tz qx qy qz qw\n"
        "1731323273.0000000000000000,0,0,0,0,0,0,1\n"
        "1731323274.0000000000000000,1,0,0,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_reference_trajectory(traj_path, gt_format="auto")

    np.testing.assert_allclose(t, np.array([1731323273.0, 1731323274.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_tum_accepts_mixed_commas_and_whitespace(tmp_path: Path) -> None:
    traj_path = tmp_path / "traj.tum"
    traj_path.write_text(
        "0, 0 0 0, 0 0 0 1\n"
        "1, 1 0 0, 0 0 0 1\n",
        encoding="utf-8",
    )

    t, pos, _ = load_estimation_tum(traj_path)

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))


def test_load_vicon_csv_with_euroc_columns(tmp_path: Path) -> None:
    csv_path = tmp_path / "gt.csv"
    csv_path.write_text(
        "#timestamp,p_RS_R_x [m],p_RS_R_y [m],p_RS_R_z [m],"
        "q_RS_x [],q_RS_y [],q_RS_z [],q_RS_w []\n"
        "1000000000,0,0,0,0,0,0,1\n"
        "2000000000,1,0,0,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_vicon_csv(csv_path)

    np.testing.assert_allclose(t, np.array([1.0, 2.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_vicon_csv_skips_comment_lines_before_header(tmp_path: Path) -> None:
    csv_path = tmp_path / "gt.csv"
    csv_path.write_text(
        "# generated by simulator\n"
        "timestamp,x,y,z,qx,qy,qz,qw\n"
        "0,0,0,0,0,0,0,1\n"
        "1,1,0,0,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_vicon_csv(csv_path)

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_trajectory_auto_csv(tmp_path: Path) -> None:
    csv_path = tmp_path / "est.csv"
    csv_path.write_text(
        "timestamp,x,y,z,qx,qy,qz,qw\n"
        "0,0,0,0,0,0,0,1\n"
        "1,1,0,0,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_trajectory(csv_path, est_format="auto")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_trajectory_auto_csv_falls_back_to_headerless_tum(tmp_path: Path) -> None:
    csv_path = tmp_path / "est.csv"
    csv_path.write_text(
        "0,0,0,0,0,0,0,1\n"
        "1,1,0,0,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_trajectory(csv_path, est_format="auto")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_reference_trajectory_auto_csv_accepts_xyz_columns(tmp_path: Path) -> None:
    csv_path = tmp_path / "gt.csv"
    csv_path.write_text(
        "timestamp,x,y,z,qx,qy,qz,qw\n"
        "0,0,0,0,0,0,0,1\n"
        "1,1,2,3,0,0,0,1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_reference_trajectory(csv_path, gt_format="auto")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[1], np.array([1.0, 2.0, 3.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_tum_sorts_and_deduplicates_timestamps(tmp_path: Path) -> None:
    traj_path = tmp_path / "traj.tum"
    traj_path.write_text(
        "2 2 0 0 0 0 0 1\n"
        "1 1 0 0 0 0 0 1\n"
        "1 99 0 0 0 0 0 1\n"
        "3 nan 0 0 0 0 0 1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_tum(traj_path)

    np.testing.assert_allclose(t, np.array([1.0, 2.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([1.0, 2.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_kitti(tmp_path: Path) -> None:
    kitti_path = tmp_path / "traj_kitti.txt"
    kitti_path.write_text(
        "1 0 0 1 0 1 0 2 0 0 1 3\n"
        "1 0 0 2 0 1 0 3 0 0 1 4\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_kitti(kitti_path)

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos, np.array([[1.0, 2.0, 3.0], [2.0, 3.0, 4.0]]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_trajectory_auto_accepts_comma_kitti(tmp_path: Path) -> None:
    kitti_path = tmp_path / "est.txt"
    kitti_path.write_text(
        "1,0,0,1,0,1,0,2,0,0,1,3\n"
        "1,0,0,2,0,1,0,3,0,0,1,4\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_trajectory(kitti_path, est_format="auto")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos, np.array([[1.0, 2.0, 3.0], [2.0, 3.0, 4.0]]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_load_estimation_trajectory_auto_kitti(tmp_path: Path) -> None:
    kitti_path = tmp_path / "est.txt"
    kitti_path.write_text(
        "1 0 0 1 0 1 0 2 0 0 1 3\n"
        "1 0 0 2 0 1 0 3 0 0 1 4\n",
        encoding="utf-8",
    )

    t, pos, _ = load_estimation_trajectory(kitti_path, est_format="auto")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([1.0, 2.0]))


def test_load_estimation_trajectory_auto_extended_tum(tmp_path: Path) -> None:
    traj_path = tmp_path / "est.txt"
    traj_path.write_text(
        "# timestamp tx ty tz qx qy qz qw covariance...\n"
        "1403715278.51214 0.002838 0.000289 0.000852 0.826838 0.001484 0.562417 0.004867 0 0 0 0\n"
        "1403715278.56214 0.006419 0.001126 0.003255 0.823966 0.000233 0.566622 0.004321 0 0 0 0\n",
        encoding="utf-8",
    )

    t, pos, quat = load_estimation_trajectory(traj_path, est_format="auto")

    assert t.shape == (2,)
    np.testing.assert_allclose(pos[:, 0], np.array([0.002838, 0.006419]))
    np.testing.assert_allclose(np.linalg.norm(quat, axis=1), np.ones(2))


def test_load_reference_trajectory_tum(tmp_path: Path) -> None:
    traj_path = tmp_path / "gt.tum"
    traj_path.write_text(
        "0 0 0 0 0 0 0 1\n"
        "1 1 0 0 0 0 0 1\n",
        encoding="utf-8",
    )

    t, pos, quat = load_reference_trajectory(traj_path, gt_format="tum")

    np.testing.assert_allclose(t, np.array([0.0, 1.0]))
    np.testing.assert_allclose(pos[:, 0], np.array([0.0, 1.0]))
    np.testing.assert_allclose(quat[:, 3], np.array([1.0, 1.0]))


def test_bag_format_requires_topic_before_rosbags_import(tmp_path: Path) -> None:
    bag_path = tmp_path / "demo.bag"
    bag_path.write_bytes(b"")

    with pytest.raises(ValueError, match="topic"):
        load_estimation_trajectory(bag_path, est_format="bag", est_topic="")


def test_bag_tf_topic_requires_parent_child_format(tmp_path: Path) -> None:
    bag_path = tmp_path / "demo.bag"
    bag_path.write_bytes(b"")

    with pytest.raises(ValueError, match="parent.child"):
        load_estimation_trajectory(bag_path, est_format="bag", est_topic="/tf:map")


def test_write_result_bundle_creates_zip_with_manifest_and_metrics(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    out_dir.mkdir()
    (out_dir / "metrics_summary.csv").write_text("section,metric,value\n", encoding="utf-8")
    (out_dir / "report_zh.md").write_text("# report zh\n", encoding="utf-8")
    (out_dir / "report_en.md").write_text("# report en\n", encoding="utf-8")
    payload = {"pose_metrics": {"ape": {"step3": {"translation_part": {"rmse": 0.1}}}}}
    bundle = write_result_bundle(out_dir, payload, tmp_path / "result.zip")
    assert bundle.exists()

    import zipfile

    with zipfile.ZipFile(bundle, "r") as zf:
        names = set(zf.namelist())
        assert "manifest.json" in names
        assert "metrics.json" in names
        assert "metrics_summary.csv" in names
        assert "report_zh.md" in names
        assert "report_en.md" in names


def test_write_run_reports_keeps_gallery_but_hides_step123_by_default(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    plots_dir = out_dir / "plots"
    plots_dir.mkdir(parents=True)
    for name in [
        "ape_translation_part_step3_series.png",
        "debug_ape_translation_part_raw.png",
        "debug_step123_trajectory_alignment_3d.png",
        "step1_time_alignment.png",
        "step3_alignment_map.png",
    ]:
        (plots_dir / name).write_bytes(b"png")

    write_run_reports(
        out_dir,
        {
            "trajectory": {"ate_rmse_step3_m": 0.1},
            "metadata": {
                "timestamp": "2026-06-12T00:00:00",
                "gt_path": "gt.tum",
                "est_path": "est.tum",
            },
        },
    )

    report = (out_dir / "report_en.md").read_text(encoding="utf-8")
    assert "## Figure Gallery" in report
    assert "## User-Facing Figures" not in report
    assert "## Debug Figures" not in report
    assert report.index("step3_alignment_map.png") < report.index("ape_translation_part_step3_series.png")
    assert "step1_time_alignment.png" in report
    assert "ape_translation_part_step3_series.png" in report
    assert "debug_ape_translation_part_raw.png" not in report
    assert "debug_step123_trajectory_alignment_3d.png" not in report


def test_write_run_reports_includes_step123_in_gallery_when_debug_enabled(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    plots_dir = out_dir / "plots"
    plots_dir.mkdir(parents=True)
    for name in [
        "debug_ape_translation_part_raw.png",
        "debug_step123_trajectory_alignment_3d.png",
        "step1_time_alignment.png",
        "step3_alignment_map.png",
    ]:
        (plots_dir / name).write_bytes(b"png")

    write_run_reports(
        out_dir,
        {
            "trajectory": {"ate_rmse_step3_m": 0.1},
            "metadata": {
                "timestamp": "2026-06-12T00:00:00",
                "gt_path": "gt.tum",
                "est_path": "est.tum",
                "debug": True,
            },
        },
    )

    report = (out_dir / "report_en.md").read_text(encoding="utf-8")
    assert "## Figure Gallery" in report
    assert "## User-Facing Figures" not in report
    assert "## Debug Figures" not in report
    assert report.index("step3_alignment_map.png") < report.index("debug_step123_trajectory_alignment_3d.png")
    assert "step1_time_alignment.png" in report
    assert "debug_ape_translation_part_raw.png" in report


def test_write_run_reports_includes_sim3_alignment_warning(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    out_dir.mkdir(parents=True)
    write_run_reports(
        out_dir,
        {
            "metric_summary": {"ape_translation_part_rmse": 0.0},
            "metadata": {
                "timestamp": "2026-06-12T00:00:00",
                "gt_path": "gt.tum",
                "est_path": "est.tum",
                "eval_alignment": {
                    "align_mode": "sim3",
                    "sim3_scale": 0.01,
                    "sim3_reliable": False,
                    "sim3_warning": "Sim3 estimated scale is outside the reliable range.",
                },
            },
            "pose_metrics": {
                "valid_segment": {
                    "step3": {
                        "success": {
                            "raw_success_rate_distance": 0.95,
                            "success_rate_distance": 0.9,
                            "raw_success_rate_time": 0.96,
                            "success_rate_time": 0.91,
                            "sr_reliability_status": "failed",
                            "sim3_may_mask_failure": True,
                            "sr_warning_explanation": "Sim3 may be masking a real trajectory failure.",
                            "sr_reliability_hard_reasons": ["sim3_may_mask_failure"],
                        }
                    }
                }
            },
        },
    )

    report = (out_dir / "report_en.md").read_text(encoding="utf-8")
    assert "## Sim3 Alignment" in report
    assert "Sim3 scale: `0.010000`" in report
    assert "Reliable: `false`" in report
    assert "outside the reliable range" in report
    assert "## Successful Rate Reliability" in report
    assert "SR distance raw / local: `95.000000%` / `90.000000%`" in report
    assert "Sim3 may mask failure: `true`" in report


def test_write_run_reports_includes_orientation_warning(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    out_dir.mkdir(parents=True)
    write_run_reports(
        out_dir,
        {
            "metric_summary": {"ape_translation_part_rmse": 0.0},
            "metadata": {
                "timestamp": "2026-06-12T00:00:00",
                "gt_path": "gt.tum",
                "est_path": "est.tum",
                "orientation_unstable": True,
                "orientation_warning": "Translation SR is high but rotation error is unstable.",
                "orientation_ape_rmse_deg": 80.0,
                "orientation_rpe_rmse_deg": 35.0,
                "orientation_rpe_time_1s_rmse_deg": 32.0,
            },
        },
    )

    report = (out_dir / "report_en.md").read_text(encoding="utf-8")
    assert "## Orientation Warning" in report
    assert "orientation_unstable" in report
    assert "APE rotation RMSE: `80.000000` deg" in report


def test_write_run_reports_highlights_time_rpe_and_pose_state_csv(tmp_path: Path) -> None:
    out_dir = tmp_path / "run"
    plots_dir = out_dir / "plots"
    plots_dir.mkdir(parents=True)
    for name in [
        "step3_alignment_map.png",
        "rpe_time_1s_translation_part_series.png",
        "rpe_time_1s_translation_part_stats.png",
        "rpe_time_1s_translation_part_box.png",
        "rpe_time_1s_translation_part_series_p95.png",
        "rpe_time_1s_translation_part_stats_core.png",
        "rpe_time_1s_translation_part_box_p95.png",
        "ape_translation_part_hist.png",
        "ape_translation_part_hist_p95.png",
        "ape_translation_part_hist_p99.png",
        "ape_translation_part_series_p95.png",
        "ape_translation_part_series_p99.png",
    ]:
        (plots_dir / name).write_bytes(b"png")
    (out_dir / "pose_states.csv").write_text("timestamp_s\n", encoding="utf-8")

    write_run_reports(
        out_dir,
        {
            "pose_metrics": {
                "rpe_time_1s": {
                    "step3": {
                        "translation_part": {"rmse": 1.2, "p95": 2.3, "max": 4.5},
                        "rotation_angle_deg": {"rmse": 6.7},
                        "pair_count": 8,
                    }
                },
                "valid_segment": {"step3": {"success": {"drift_rpe_1s_m": 2.0}}},
            },
            "case_diagnostics": {
                "diagnosis_primary": "trajectory_jump",
                "diagnosis_summary": "trajectory_jump; global_gate_too_large",
                "diagnosis_tags": ["trajectory_jump", "global_gate_too_large"],
                "diagnosis_reasons": {
                    "trajectory_jump": "global/local segment error ratio is large",
                },
            },
            "metadata": {
                "timestamp": "2026-06-12T00:00:00",
                "gt_path": "gt.tum",
                "est_path": "est.tum",
                "pose_state_csv": str(out_dir / "pose_states.csv"),
            },
        },
    )

    report = (out_dir / "report_en.md").read_text(encoding="utf-8")
    assert "## Case Diagnostics" in report
    assert "trajectory_jump" in report
    assert "## 1-second RPE (Local Jumps)" in report
    assert "Final aligned translation RMSE: `1.200000` m" in report
    assert "[pose_states.csv](pose_states.csv)" in report
    assert report.index("ape_translation_part_hist_p95.png") < report.index("ape_translation_part_hist.png")
    assert report.index("ape_translation_part_series_p95.png") < report.index("ape_translation_part_hist.png")
    assert report.index("rpe_time_1s_translation_part_series_p95.png") < report.index(
        "rpe_time_1s_translation_part_series.png"
    )
    assert report.index("ape_translation_part_hist_p95.png") < report.index("ape_translation_part_hist.png")


def test_write_pose_state_csv_exports_pose_and_velocity(tmp_path: Path) -> None:
    t = np.array([0.0, 1.0, 2.0])
    pos = np.column_stack([t, np.zeros_like(t), np.zeros_like(t)])
    quat = R.from_euler("z", [0.0, 0.5, 1.0]).as_quat()

    out = write_pose_state_csv(
        tmp_path / "pose_states.csv",
        timestamps_s=t,
        stages={"gt": (pos, quat), "step3": (pos, quat)},
    )

    rows = out.read_text(encoding="utf-8").strip().splitlines()
    header = rows[0].split(",")
    values = rows[1].split(",")
    assert "gt_px" in header
    assert "gt_qw" in header
    assert "gt_vx" in header
    assert "gt_wz" in header
    assert len(rows) == 4
    vx = float(values[header.index("gt_vx")])
    wz = float(values[header.index("gt_wz")])
    np.testing.assert_allclose(vx, 1.0)
    np.testing.assert_allclose(wz, 0.5)


def test_make_output_dir_retries_existing_timestamp_names(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    class FixedDateTime:
        @classmethod
        def now(cls):
            return cls()

        def strftime(self, fmt: str) -> str:
            return "run_20260101_000000"

    monkeypatch.setattr("epa.core.io_utils.datetime", FixedDateTime)
    output_root = tmp_path / "outputs"

    first = make_output_dir(tmp_path, output_root=output_root)
    second = make_output_dir(tmp_path, output_root=output_root)
    third = make_output_dir(tmp_path, output_root=output_root)

    assert first.name == "run_20260101_000000"
    assert second.name == "run_20260101_000000_01"
    assert third.name == "run_20260101_000000_02"


def test_make_output_dir_uses_safe_run_label(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    class FixedDateTime:
        @classmethod
        def now(cls):
            return cls()

        def strftime(self, fmt: str) -> str:
            return "run_20260101_000000"

    monkeypatch.setattr("epa.core.io_utils.datetime", FixedDateTime)
    output_root = tmp_path / "outputs"

    first = make_output_dir(tmp_path, output_root=output_root, run_label="demo case/01")
    second = make_output_dir(tmp_path, output_root=output_root, run_label="demo case/01")

    assert first.name == "run_20260101_000000_demo_case_01"
    assert second.name == "run_20260101_000000_demo_case_01_01"
